### ISSUE TITLE
INFOGRAFIA DE LOS LENGUAJES DE PROGRAMACION EN CONTRATOS INTELIGENTES

### ISSUE THREAD

**Issue by Rmz-Rigo** [SistemasTecTlaxiaco/infografia-lenguajes-de-programacion-Rigoberto2001#1]
[INFOGRAFIA_RIGOBERTORAMIREZNICOLAS.pdf](https://github.com/SistemasTecTlaxiaco/infografia-lenguajes-de-programacion-Rigoberto2001/files/8467680/INFOGRAFIA_RIGOBERTORAMIREZNICOLAS.pdf)

**Comment by AndreLuna6** [comment]
Calificación: 20/20

Partes de una infografía: 4
-Coherencia y pertenencia: 4
-Organización de
la información: 4
-Diseño y
composición de
la infografía: 4
-Creatividad: 4

**Comment by josealfredo79** [comment]
Bien hecho y revisado
